### ISSUE TITLE
Should exit with error on empty interactions array

### ISSUE THREAD

**Issue by crpc** [HLTech/pact-gen-ts#54]
Sometimes pact-gen-ts exits with error code 0 while not generating any interactions (for example when using with TypeScript 4.4 - [issue tracked here](https://github.com/HLTech/pact-gen-ts/issues/55)).

I think this should always be treated as an error state with proper message.

If having no interactions with given provider is intentional, we should suggest removing config for this provider entirely.

**Comment by pawfa** [comment]
I can work on that. What do you think best error information would be? 
Simple `Pact interactions for provider: example-provider-name and consumer: example-consumer-name are empty.` for each pact would be enough?
